version: "3"

services:

  runtime-setup:
    image: swift-memcache-gsoc:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  test:
    image: swift-memcache-gsoc:22.04-5.7
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      # - SANITIZER_ARG=--sanitize=thread # TSan broken still

  shell:
    image: swift-memcache-gsoc:22.04-5.7

  update-benchmark-baseline:
    image: swift-memcache-gsoc:22.04-5.7